Linear regression using numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
np.set_printoptions(precision=2)  # reduced display precision on numpy arrays

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           |  


In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [3]:
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [4]:
b_init = 0
w_init = np.zeros(4)
print(w_init)

[0. 0. 0. 0.]


In [5]:
def predict(w, x, b):
    """
    single predict using linear regression
    Args:
      x (ndarray): Shape (n,) example with multiple features
      w (ndarray): Shape (n,) model parameters   
      b (scalar):             model parameter 

    Returns:
      p (scalar):  prediction
    """
    return np.dot(w, x)+b

In [6]:
def compute_cost(X, w, b, y):
    """
       compute cost
       Args:
         X (ndarray (m,n)): Data, m examples with n features
         y (ndarray (m,)) : target values
         w (ndarray (n,)) : model parameters  
         b (scalar)       : model parameter

       Returns:
         cost (scalar): cost
       """

    m = X.shape[0]
    cost = 0
    for i in range(m):
        y_pred = predict(w, X[i], b)
        cost += (y_pred-y[i])**2

    return cost/(2*m)

In [7]:
# Compute and display cost using our pre-chosen optimal parameters.
cost = compute_cost(X_train, w_init, b_init, y_train)
print(f'Cost at initial w : {cost}')

Cost at initial w : 49518.0


In [8]:
def compute_gradient(X, y, w, b):
    """
    Computes the gradient for linear regression 
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters  
      b (scalar)       : model parameter

    Returns:
      dj_dw (ndarray (n,)): The gradient of the cost w.r.t. the parameters w. 
      dj_db (scalar):       The gradient of the cost w.r.t. the parameter b. 
    """
    m, n = X.shape
    dj_dw = np.zeros((n,))

    dj_db = 0.

    for i in range(m):
        err = (np.dot(X[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [9]:
# Compute and display gradient
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -290.0
dj_dw at initial w,b: 
 [-4.83e+05 -1.12e+03 -3.67e+02 -1.21e+04]


In [10]:
def gradient_descent(X, y, w_in, b_in, alpha, iter, cost_function, gradient_function):
    """
    Performs batch gradient descent to learn w and b. Updates w and b by taking 
    num_iters gradient steps with learning rate alpha

    Args:
      X (ndarray (m,n))   : Data, m examples with n features
      y (ndarray (m,))    : target values
      w_in (ndarray (n,)) : initial model parameters  
      b_in (scalar)       : initial model parameter
      cost_function       : function to compute cost
      gradient_function   : function to compute the gradient
      alpha (float)       : Learning rate
      num_iters (int)     : number of iterations to run gradient descent

    Returns:
      w (ndarray (n,)) : Updated values of parameters 
      b (scalar)       : Updated value of parameter 
      """

    # An array to store cost J and w's at each iteration primarily for graphing later
    w = copy.deepcopy(w_in)  # avoid modifying global w within function
    b = b_in

    for i in range(iter):
        # calculate gradient
        tmp_dj_db, tmp_dj_dw = gradient_function(X, y, w, b)
        print(tmp_dj_db)
        print(tmp_dj_dw)
        # update parameters
        w = w-alpha*tmp_dj_dw
        b = b-alpha*tmp_dj_db

    return w, b

In [15]:
def predict(X, w, b, y_target):
    y_pred = np.dot(X, w)+b
    diff = abs(y_pred-y_target)
    print('Predicted value is: '+str(y_pred)+' , target value: ' +
          str(y_target)+', with a difference of: ' + str(diff))
    return y_pred

In [24]:
predict(X_train[0], w_final, b_final, y_train[0])

Predicted value is: 425.65137616474397 , target value: 460, with a difference of: 34.348623835256035


425.65137616474397

In [22]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 50000
alpha = 1e-9
# run gradient descent
w_final, b_final = gradient_descent(
    X_train, y_train, initial_w, initial_b, alpha, iterations, compute_cost, compute_gradient)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m, _ = X_train.shape
for i in range(m):
    print(
        f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

-290.0
[-4.83e+05 -1.12e+03 -3.67e+02 -1.21e+04]
-289.29610258733334
[-4.82e+05 -1.11e+03 -3.66e+02 -1.20e+04]
-288.59388570865536
[-4.80e+05 -1.11e+03 -3.65e+02 -1.20e+04]
-287.8933453517441
[-4.79e+05 -1.11e+03 -3.65e+02 -1.20e+04]
-287.19447751395666
[-4.78e+05 -1.11e+03 -3.64e+02 -1.20e+04]
-286.49727820220625
[-4.77e+05 -1.10e+03 -3.63e+02 -1.19e+04]
-285.80174343293965
[-4.76e+05 -1.10e+03 -3.62e+02 -1.19e+04]
-285.10786923211407
[-4.75e+05 -1.10e+03 -3.61e+02 -1.19e+04]
-284.41565163517464
[-4.74e+05 -1.10e+03 -3.60e+02 -1.18e+04]
-283.72508668703176
[-4.72e+05 -1.09e+03 -3.59e+02 -1.18e+04]
-283.0361704420385
[-4.71e+05 -1.09e+03 -3.58e+02 -1.18e+04]
-282.34889896396805
[-4.70e+05 -1.09e+03 -3.57e+02 -1.18e+04]
-281.6632683259913
[-4.69e+05 -1.09e+03 -3.56e+02 -1.17e+04]
-280.97927461065393
[-4.68e+05 -1.08e+03 -3.55e+02 -1.17e+04]
-280.296913909855
[-4.67e+05 -1.08e+03 -3.54e+02 -1.17e+04]
-279.61618232482357
[-4.66e+05 -1.08e+03 -3.54e+02 -1.16e+04]
-278.9370759660972
[-4.65e